GET http://localhost:3000/auth/profile
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6InBwcDExMUBleGFtcGxlLmNvbSIsImlhdCI6MTczNTEwODAzOSwiZXhwIjoxNzM1MTA4MDk5fQ.OARBA3rVxaVfSmRGmyvozkTt0IsMTw5aBf3RKrsteo8
###




POST http://localhost:3000/auth/login

{
    "email":"ppp111@example.com",
  "password": "Kiet@18072002"
}